### ISSUE TITLE
Bug in EnableChannelInterrupt method

### ISSUE THREAD

**Issue by zalg** [pichenettes/avrilx#3]
Hello! I think I have found a bug in [timer.h](https://github.com/pichenettes/avrilx/blob/master/system/timer.h) file in _EnableChannelInterrupt_ and _DisableChannelInterrupt_ methods of _Timer_ class. Value of _shift_ local variable can never be less than 4. So this means that _mask_ can never be equal to 0x0C, and this means that you can never set _CCBINTLVL_ bits. 
Also in _TimerChannel_ enum you don't give direct values for _TIMER_CHANNEL_x_ options, but in examples you propose to use it as channel argument of these functions (which is uint_8t). Can't a compiler sometime by itself define them a way different from 0,1,2,3?

**Comment by pichenettes** [comment]
I haven't worked on an ATXmega project for the past 8 years so this completely left my head.

I believe this fixes the problem you highlighted, but I don't have any device to test.
https://github.com/pichenettes/avrilx/commit/97cfb7e3bb5edf92399bccc26610ea1a33ecfbd9
